
# A string used to distinguish different Supabase projects on the same host. Defaults to the project ID.
project_id = "bjuzoovrgsozkcdgrxnj"

[api]
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. Public and auth schemas are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# Maximum rows returns in a single response. Defaults to 1000.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# Port used by database to listen for connections.
listen_port = 5432
# The password to use when connecting to the database.
password = "postgres"

[functions.create-storage-bucket]
verify_jwt = false
