// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjuzoovrgsozkcdgrxnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqdXpvb3ZyZ3NvemtjZGdyeG5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NTA3OTYsImV4cCI6MjA2MDIyNjc5Nn0.XgmNghYME-DHklp47eR8dTNEEW6yVLhUVoBTJsf5mG0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);